/**
 * Search module - provides full-text search over documentation
 *
 * Import from '@octavus/docs/search' to use search functionality.
 * The search index is pre-built at package build time.
 */

import MiniSearch from 'minisearch';
import type { SearchResult } from './types';

// Re-export types for consumers
export type { SearchResult } from './types';

// Search index is generated by prebuild script
import searchIndexData from '../dist/search-index.json';

interface IndexedDoc {
  id: number;
  slug: string;
  title: string;
  section: string;
  excerpt: string;
}

// Load pre-built search index
const searchIndex = MiniSearch.loadJSON<IndexedDoc>(JSON.stringify(searchIndexData), {
  fields: ['title', 'content', 'section'],
  storeFields: ['title', 'slug', 'section', 'excerpt'],
});

/**
 * Search documentation by query string.
 *
 * @param query - The search query
 * @param limit - Maximum number of results (default: 10)
 * @returns Array of search results sorted by relevance
 */
export function searchDocs(query: string, limit = 10): SearchResult[] {
  if (!query || query.length < 2) return [];

  const results = searchIndex.search(query, {
    prefix: true,
    fuzzy: 0.2,
    boost: { title: 2 },
  });

  return results.slice(0, limit).map((result) => ({
    slug: result.slug,
    title: result.title,
    section: result.section,
    excerpt: result.excerpt,
    score: result.score,
  }));
}
